### ISSUE TITLE
How do I implement on my own dataset

### ISSUE THREAD

**Issue by Zumbalamambo** [TropComplique/ShuffleNet-tensorflow#2]
I have got series of folders containing various image data. How do I train with this data as in mobilenet?

**Comment by TropComplique** [comment]
1. Convert your data to tfrecords files with `image_dataset_to_tfrecords.py`.
2. Change number of layers and complexity of the network as you like
in `src/parts_of_the_net.py` file. Look for `_mapping` function.
3. Use `train.ipynb` notebook to train.

I trained ShuffleNet on tiny-imagenet dataset, so I made a couple of changes to the original ShuffleNet architecture. For example, I use `stride=1` in the first conv layer instead of `stride=2`.

Later, I will add more documentation and comments to the project.

**Comment by juzhitao** [comment]
where is src/parts_of_the_net.py？

**Comment by TropComplique** [comment]
I renamed it as `shufflenet/architecture.py`.
